import express from "express";
import auth from "./auth";
import materialGrades from "./materials/materialGrades";
import materialGroups from "./materials/materialGroups";
import materialNames from "./materials/materialNames";
import materialProviders from "./materials/materialProviders";
import partNames from "./parts/partNames";
import partGroups from "./parts/partGroups";
import partsGeneralIds from "./parts/partsGeneralIds";
import partProviders from "./parts/partProviders";
import getAll from "./getAll";
import exhibition from "./exhibition";
import digitalMagazine from "./digitalMagazine";
import podcast from "./podcast";
import messages from "./messages";
import offer from "./offer";
import products from "./products";
import resourceCenter from "./resourceCenter";
import marketInformation from "./marketInformation";
import userTickets from "./userTickets";
import providerTickets from "./providerTickets";
import rating from "./rating";
import comment from "./comment";
const router = express.Router();

export default (): express.Router => {
  auth(router);
  materialGrades(router);
  materialGroups(router);
  materialNames(router);
  materialProviders(router);
  partNames(router);
  partGroups(router);
  partsGeneralIds(router);
  partProviders(router);
  getAll(router);
  exhibition(router);
  digitalMagazine(router);
  podcast(router);
  messages(router);
  offer(router);
  products(router);
  resourceCenter(router);
  marketInformation(router);
  userTickets(router);
  providerTickets(router);
  rating(router);
  comment(router);

  return router;
};
